/* ============================================================================
 *  Analytics — Weekly Rollup History
 *  COWORK WRITE-BACK CONTRACT — Added 2026-04-06 handoff
 *  weekly_metrics_rollups rows written by Cowork "Friday Metrics Rollup"
 *  scheduled task (Fridays) via Supabase MCP (service_role key).
 *  DO NOT REMOVE — this page is the full history view for rollups.
 *  The Overview page shows only the most recent rollup; this page shows
 *  up to 8 weeks with expand/collapse.
 * ============================================================================ */

import { useEffect, useState } from 'react'
import { apiGet } from '../../lib/api'
import SEO from '../../components/SEO'

interface WeeklyRollup {
  id: string
  week_start: string
  narrative: string
  metrics: Record<string, number>
  highlights: Array<{ category: string; text: string }>
  created_at: string
}

export default function Analytics() {
  const [rollups, setRollups] = useState<WeeklyRollup[]>([])
  const [loading, setLoading] = useState(true)
  const [expandedId, setExpandedId] = useState<string | null>(null)

  useEffect(() => {
    apiGet<WeeklyRollup[]>('/api/analytics/rollups?limit=8')
      .then(data => {
        setRollups(data)
        if (data.length > 0) setExpandedId(data[0].id)
      })
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [])

  return (
    <>
      <SEO title="Analytics — BaxterLabs" description="Weekly metrics rollups" />

      <div className="mb-6">
        <h1 className="text-2xl font-bold text-charcoal font-display">Analytics</h1>
        <p className="text-sm text-charcoal/60 mt-1">Weekly metrics rollups — generated by Cowork on Fridays</p>
      </div>

      <div className="space-y-3">
        {loading ? (
          Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="bg-white rounded-lg border border-gray-200 p-5 animate-pulse">
              <div className="h-5 bg-gray-200 rounded w-1/3 mb-3" />
              <div className="h-3 bg-gray-200 rounded w-full mb-2" />
              <div className="h-3 bg-gray-200 rounded w-2/3" />
            </div>
          ))
        ) : rollups.length === 0 ? (
          <div className="bg-white rounded-lg border border-gray-200 p-12 text-center">
            <svg className="w-10 h-10 mx-auto text-charcoal/20 mb-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z" />
            </svg>
            <p className="text-sm text-charcoal/40">No rollups yet. Cowork generates these on Fridays.</p>
          </div>
        ) : (
          rollups.map(rollup => {
            const isExpanded = expandedId === rollup.id
            const weekLabel = new Date(rollup.week_start + 'T00:00:00').toLocaleDateString('en-US', {
              month: 'long', day: 'numeric', year: 'numeric',
            })

            return (
              <div key={rollup.id} className="bg-white rounded-lg border border-gray-200">
                {/* Collapsible header */}
                <button
                  onClick={() => setExpandedId(isExpanded ? null : rollup.id)}
                  className="w-full flex items-center justify-between p-5 text-left hover:bg-ivory/50 transition-colors"
                >
                  <div>
                    <h3 className="text-sm font-bold text-charcoal">Week of {weekLabel}</h3>
                    <p className="text-xs text-charcoal/40 mt-0.5 line-clamp-1">{rollup.narrative}</p>
                  </div>
                  <svg
                    className={`w-4 h-4 text-charcoal/40 transition-transform flex-shrink-0 ml-3 ${isExpanded ? 'rotate-180' : ''}`}
                    fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                  </svg>
                </button>

                {/* Expanded content */}
                {isExpanded && (
                  <div className="px-5 pb-5 border-t border-gray-100">
                    <p className="text-sm text-charcoal/70 mt-4 mb-4">{rollup.narrative}</p>

                    {/* Metrics grid */}
                    {Object.keys(rollup.metrics).length > 0 && (
                      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
                        {Object.entries(rollup.metrics).map(([key, val]) => (
                          <div key={key} className="text-center py-2 bg-ivory rounded-lg">
                            <div className="text-lg font-bold text-charcoal">
                              {typeof val === 'number' && key.includes('value')
                                ? `$${(val / 1000).toFixed(0)}K`
                                : typeof val === 'number' && key.includes('rate')
                                  ? `${val}%`
                                  : val}
                            </div>
                            <div className="text-[10px] text-charcoal/50 font-medium">
                              {key.replace(/_/g, ' ')}
                            </div>
                          </div>
                        ))}
                      </div>
                    )}

                    {/* Highlights */}
                    {rollup.highlights.length > 0 && (
                      <div className="space-y-1.5">
                        {rollup.highlights.map((h, i) => (
                          <div key={i} className="flex items-start gap-2">
                            <span className={`flex-shrink-0 mt-1 w-1.5 h-1.5 rounded-full ${
                              h.category === 'win' ? 'bg-emerald-500' :
                              h.category === 'flag' ? 'bg-amber-500' :
                              'bg-blue-400'
                            }`} />
                            <p className="text-xs text-charcoal/60">{h.text}</p>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}
              </div>
            )
          })
        )}
      </div>
    </>
  )
}
