-- ============================================================================
-- 062_pipeline_briefings.sql
-- Created: 2026-04-06
-- Purpose: Store daily pipeline priority briefings generated by Cowork
--          scheduled task "Pipeline Priority Briefing" (weekdays 7:00 AM PT).
--
-- Write-back contract (Cowork → Supabase MCP):
--   Cowork writes one row per weekday via execute_sql with service_role key.
--   Required fields: briefing_date, pipeline_status, follow_ups_due,
--                    priority_actions, raw_analysis.
--   Dashboard reads via FastAPI GET /api/pipeline/briefings.
--   No FastAPI POST endpoint exists — all writes are Cowork-only.
-- ============================================================================

CREATE TABLE pipeline_briefings (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  briefing_date    DATE NOT NULL UNIQUE,
  pipeline_status  TEXT NOT NULL,
  follow_ups_due   JSONB NOT NULL DEFAULT '[]',
  priority_actions JSONB NOT NULL DEFAULT '[]',
  raw_analysis     TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_pipeline_briefings_date
  ON pipeline_briefings(briefing_date DESC);

ALTER TABLE pipeline_briefings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON pipeline_briefings
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
