-- ============================================================================
-- 063_weekly_metrics_rollups.sql
-- Created: 2026-04-06
-- Purpose: Store weekly metrics rollup narratives generated by Cowork
--          scheduled task "Friday Metrics Rollup" (Fridays).
--
-- Write-back contract (Cowork → Supabase MCP):
--   Cowork writes one row per week (keyed on week_start = Monday date)
--   via execute_sql with service_role key.
--   Required fields: week_start, narrative, metrics, highlights.
--   Dashboard reads via FastAPI GET /api/analytics/rollups.
--   No FastAPI POST endpoint exists — all writes are Cowork-only.
-- ============================================================================

CREATE TABLE weekly_metrics_rollups (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  week_start  DATE NOT NULL UNIQUE,
  narrative   TEXT NOT NULL,
  metrics     JSONB NOT NULL DEFAULT '{}',
  highlights  JSONB NOT NULL DEFAULT '[]',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_weekly_metrics_week
  ON weekly_metrics_rollups(week_start DESC);

ALTER TABLE weekly_metrics_rollups ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON weekly_metrics_rollups
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
