-- ============================================================================
-- 064_commenting_opportunities.sql
-- Created: 2026-04-06
-- Purpose: Store daily LinkedIn commenting opportunities generated by Cowork
--          scheduled task "LinkedIn Commenting Pre-Brief" (weekdays).
--
-- Write-back contract (Cowork → Supabase MCP):
--   Cowork writes 5 rows per weekday (rank 1-5) via execute_sql with
--   service_role key. The UNIQUE(briefing_date, rank) constraint prevents
--   duplicates on retry.
--   Required fields: briefing_date, rank, profile_name, profile_url,
--                    post_summary, relevance_reason, suggested_angle.
--   Dashboard reads via FastAPI GET /api/content/commenting.
--   Status updates via FastAPI PATCH /api/content/commenting/{id}.
--   No FastAPI POST endpoint exists — all writes are Cowork-only.
-- ============================================================================

CREATE TABLE commenting_opportunities (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  briefing_date     DATE NOT NULL,
  rank              INTEGER NOT NULL CHECK (rank BETWEEN 1 AND 5),
  profile_name      TEXT NOT NULL,
  profile_url       TEXT NOT NULL,
  post_summary      TEXT NOT NULL,
  relevance_reason  TEXT NOT NULL,
  suggested_angle   TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'acted_on', 'skipped', 'saved')),
  acted_at          TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (briefing_date, rank)
);

CREATE INDEX idx_commenting_opps_date
  ON commenting_opportunities(briefing_date DESC);

CREATE INDEX idx_commenting_opps_pending
  ON commenting_opportunities(status)
  WHERE status = 'pending';

ALTER TABLE commenting_opportunities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "authenticated_full_access" ON commenting_opportunities
  FOR ALL TO authenticated USING (true) WITH CHECK (true);
